module.exports = {
  PASSWORD_INVALID: 'PASSWORD_INVALID',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  NOT_FOUND: 'NOT_FOUND',
  TOKEN_INVALID: 'TOKEN_INVALID',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  CREDENTIALS_IVALID: 'CREDENTIALS_IVALID',
  USER_DISABLED: 'USER_DISABLED',
  NOT_MODEL: 'NOT_MODEL',

  // Successful
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
};
